/**
 * Markdown Export Module
 * Exports content from all pages to Markdown format
 */

/**
 * Export Flying Wheel / Operations Sheet content to Markdown
 */
async function exportStagesToMarkdown() {
    try {
        const response = await fetch('data/stages-data.json');
        const data = await response.json();
        
        let markdown = `# The Pigeon Way - Intelligence Operational Sheet\n\n`;
        markdown += `**Version:** ${data.version}\n\n`;
        markdown += `---\n\n`;
        
        data.stages.forEach((stage, index) => {
            markdown += `## ${stage.step}. ${stage.title}\n\n`;
            markdown += `**Promise:** ${stage.promise}\n\n`;
            markdown += `${stage.description}\n\n`;
            markdown += `**Engine:** ${stage.engine}\n\n`;
            
            // People
            markdown += `### Our People\n\n`;
            markdown += `**The Experts:** ${stage.people.experts}\n\n`;
            markdown += `**The Coordinators:** ${stage.people.coordinators}\n\n`;
            
            // Front Processes
            markdown += `### The Front Processes\n\n`;
            stage.processes.forEach(proc => {
                const statusBadge = proc.status === 'new' ? '🆕 NEW' : 
                                   proc.status === 'active' ? '✅ Active' : 
                                   proc.status === 'merge' ? '🔄 Merge' : 
                                   proc.status === 'todo' ? '📋 To implement' : '';
                markdown += `- **${proc.name}** ${statusBadge}\n`;
            });
            markdown += `\n`;
            
            // TDR Information
            if (stage.tdr) {
                markdown += `### Documentation Standard (${stage.tdr.target}) and AI Potential\n\n`;
                markdown += `**Tier:** ${stage.tdr.tier} (${getTierLabel(stage.tdr.tier)})\n\n`;
                markdown += `**The Rule:** ${stage.tdr.rule}\n\n`;
                markdown += `**What to Document:**\n`;
                stage.tdr.documentation.forEach(doc => {
                    markdown += `- ${doc}\n`;
                });
                markdown += `\n`;
                markdown += `**The AI Implication:** ${stage.tdr.aiImplication}\n\n`;
            }
            
            // Back Process
            markdown += `### The Back Process\n\n`;
            stage.backProcess.forEach(backProc => {
                markdown += `**${backProc.title}**\n`;
                markdown += `${backProc.desc}\n\n`;
            });
            
            markdown += `---\n\n`;
        });
        
        // Download
        downloadMarkdown(markdown, 'pigeon-way-operations-sheet.md');
    } catch (error) {
        console.error('Error exporting stages:', error);
        alert('Error exporting content. Please try again.');
    }
}

/**
 * Export Ops Rationale content to Markdown
 */
function exportOpsRationaleToMarkdown() {
    const content = document.querySelector('.bg-white.rounded-xl');
    if (!content) {
        alert('Could not find content to export.');
        return;
    }
    
    let markdown = `# The Digital Readiness Standard\n\n`;
    markdown += `## The Logic of TDR Targets\n\n`;
    
    // TDR Definition
    markdown += `### What is TDR?\n\n`;
    markdown += `**Total Documentation Rate (TDR)** is the percentage of total tasks that are actively documented.\n\n`;
    markdown += `---\n\n`;
    
    // Methodology
    markdown += `## Methodology & Calibration Framework\n\n`;
    markdown += `### The Core Philosophy: "Risk vs. Velocity"\n\n`;
    markdown += `In modern process management, "One Size Fits All" is a failure mode. Holding a Creative Director to the documentation standards of a Brain Surgeon is not just unfair—it is operationally destructive.\n\n`;
    markdown += `Our framework calibrates the Total Documentation Rate (TDR) target based on a single sliding scale: The trade-off between Operational Velocity (Speed) and Risk Mitigation (Control).\n\n`;
    markdown += `We categorize every industry and department into three distinct tiers.\n\n`;
    markdown += `---\n\n`;
    
    // Tier 1
    markdown += `## TIER 1: The "Agile & Relational" Tier\n\n`;
    markdown += `**Targets:** 20% – 35%\n\n`;
    markdown += `### Focus: Speed, Talent, and Volume\n\n`;
    markdown += `In this tier, value is generated by human talent (Hard Skills) or high-volume execution. Excessive documentation here creates friction that kills revenue. We do not document "how" to do the job (which is talent-based), but "how" the job is tracked (admin).\n\n`;
    markdown += `### The Rule: Protect the Magic, Document the Container\n\n`;
    markdown += `#### Creative Ideation (20%)\n\n`;
    markdown += `The boldest target. We exempt 80% of the work because you cannot write a Standard Operating Procedure (SOP) for "having a good idea." We only document the brief and the approval.\n\n`;
    markdown += `#### Sales (30%)\n\n`;
    markdown += `Sales agility is paramount. We demand documentation only for the CRM (Deal Stages) and Pricing. The rest is relationship management.\n\n`;
    markdown += `#### Marketing (35%)\n\n`;
    markdown += `Similar to Creative, but with higher requirements for Brand Consistency and Campaign Briefs to protect ROI.\n\n`;
    markdown += `### The AI Implication\n\n`;
    markdown += `Automation here focuses on administrative offloading (e.g., Lead Scrapping, CRM data entry and enhancement, Proposals and Presentations automation...) rather than replacing the core task.\n\n`;
    markdown += `---\n\n`;
    
    // Tier 2
    markdown += `## TIER 2: The "Technical & Strategic" Tier\n\n`;
    markdown += `**Targets:** 40% – 50%\n\n`;
    markdown += `### Focus: Reproducibility and Technical Debt\n\n`;
    markdown += `This is the pivot point. These industries rely on complex intellectual property. If the process isn't documented, the product becomes "fragile"—it breaks when the creator leaves. We document to ensure work is reusable.\n\n`;
    markdown += `### The Rule: The Code is the Truth, but the Specs are the Map\n\n`;
    markdown += `#### Creative Production (40%)\n\n`;
    markdown += `Unlike Ideation, Production (resizing, asset management, file naming) must be consistent. This is the factory floor of the agency.\n\n`;
    markdown += `#### Strategy & Consulting (50%)\n\n`;
    markdown += `The perfect balance. The deliverable is the document. We document the methodology to ensure the firm's intellectual property doesn't walk out the door with the consultant.\n\n`;
    markdown += `#### IT Support (50%)\n\n`;
    markdown += `The "AI Sweet Spot." You need a Knowledge Base (KB) to solve tickets fast. If you document 50% of common issues, AI can deflect them.\n\n`;
    markdown += `### The AI Implication\n\n`;
    markdown += `AI Agents. Since the "Rules" are written, AI Agents can draft strategy outlines, conduct competitive research, and summarize insights.\n\n`;
    markdown += `---\n\n`;
    
    // Tier 3
    markdown += `## TIER 3: The "Compliance & Safety" Tier\n\n`;
    markdown += `**Targets:** 55% – 80%\n\n`;
    markdown += `### Focus: Risk Mitigation, Safety, and Law\n\n`;
    markdown += `In this tier, the cost of an error is not "lost time"—it is a lawsuit, an injury, or a regulatory fine. Documentation is not a "nice to have"; it is a legal shield.\n\n`;
    markdown += `### The Rule: If it isn't written down, it didn't happen\n\n`;
    markdown += `#### Finance (60%)\n\n`;
    markdown += `Driven by Auditability. We document to prove to the government (and shareholders) that the money is real.\n\n`;
    markdown += `#### HR (65%)\n\n`;
    markdown += `Higher than Finance? Yes. Human processes (hiring/firing) are messier and carry higher litigation risk than balanced ledgers. An undocumented firing is a guaranteed lawsuit.\n\n`;
    markdown += `#### Legal (80%)\n\n`;
    markdown += `The ceiling. Here, the document is the operation. Precision is more valuable than speed.\n\n`;
    markdown += `### The AI Implication\n\n`;
    markdown += `AI agents are transforming daily work by automating routine tasks like answering employee questions, building presentations, creating financial reports, and resolving support requests using company documents—boosting efficiency, reducing manual effort, and helping teams focus on growth and customer needs.\n\n`;
    
    // Download
    downloadMarkdown(markdown, 'ops-rationale.md');
}

/**
 * Export all content to Markdown
 */
async function exportAllToMarkdown() {
    try {
        // Export stages
        await exportStagesToMarkdown();
        
        // Wait a bit, then export rationale
        setTimeout(() => {
            // For rationale, we need to be on that page or fetch it
            // For now, just export stages and show message
            alert('Operations Sheet exported. Please navigate to Ops Rationale page to export that content separately, or it will be included in the next update.');
        }, 500);
    } catch (error) {
        console.error('Error exporting all:', error);
        alert('Error exporting content. Please try again.');
    }
}

/**
 * Download markdown content as file
 * @param {string} content - Markdown content
 * @param {string} filename - Filename for download
 */
function downloadMarkdown(content, filename) {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

/**
 * Get tier label
 * @param {number} tier - Tier number
 * @returns {string} Tier label
 */
function getTierLabel(tier) {
    const labels = {
        1: 'Agile & Relational',
        2: 'Technical & Strategic',
        3: 'Compliance & Safety'
    };
    return labels[tier] || 'Unknown';
}

/**
 * Export current page content
 * @param {string} pageType - Type of page: 'flying-wheel', 'operations-sheet', 'ops-rationale'
 */
async function exportCurrentPage(pageType) {
    switch(pageType) {
        case 'flying-wheel':
        case 'operations-sheet':
            await exportStagesToMarkdown();
            break;
        case 'ops-rationale':
            exportOpsRationaleToMarkdown();
            break;
        default:
            await exportAllToMarkdown();
    }
}

// Expose globally
window.exportStagesToMarkdown = exportStagesToMarkdown;
window.exportOpsRationaleToMarkdown = exportOpsRationaleToMarkdown;
window.exportAllToMarkdown = exportAllToMarkdown;
window.exportCurrentPage = exportCurrentPage;

